from pathlib import Path

path = Path(__file__).resolve().parents[2] / "crates/rom-server/src/game_interaction.rs"
text = path.read_text(encoding="utf-8")
old = '''    #[test]\n    fn block_drop_enters_world_item_simulation() {'''
new = '''    #[test]\n    fn block_drop_obeys_pickup_delay_and_enters_inventory() {\n        use std::num::NonZeroUsize;\n\n        let runtime = SharedGameRuntime::vanilla_overworld();\n        let uuid = PlayerUuid::new(3);\n        runtime.connect_player(uuid, "Notch", spawn()).unwrap();\n        let subscription = runtime.subscribe(NonZeroUsize::new(32).unwrap()).unwrap();\n        let entity_id = runtime\n            .spawn_world_item(\n                uuid,\n                [0.0, 64.0, 0.0],\n                ItemStack::new("minecraft:cobblestone", 1).unwrap(),\n            )\n            .unwrap();\n\n        for _ in 0..9 {\n            runtime.tick().unwrap();\n        }\n        assert!(\n            runtime\n                .with_state(|state| state.entities().get(entity_id).is_some())\n                .unwrap()\n        );\n        let before = runtime\n            .with_state(|state| {\n                state\n                    .player(uuid)\n                    .unwrap()\n                    .inventory\n                    .slots()\n                    .iter()\n                    .flatten()\n                    .filter(|stack| stack.item() == "minecraft:cobblestone")\n                    .map(ItemStack::count)\n                    .sum::<u32>()\n            })\n            .unwrap();\n        assert_eq!(before, 0);\n\n        runtime.tick().unwrap();\n\n        assert!(\n            runtime\n                .with_state(|state| state.entities().get(entity_id).is_none())\n                .unwrap()\n        );\n        let after = runtime\n            .with_state(|state| {\n                state\n                    .player(uuid)\n                    .unwrap()\n                    .inventory\n                    .slots()\n                    .iter()\n                    .flatten()\n                    .filter(|stack| stack.item() == "minecraft:cobblestone")\n                    .map(ItemStack::count)\n                    .sum::<u32>()\n            })\n            .unwrap();\n        assert_eq!(after, 1);\n\n        let events = std::iter::from_fn(|| subscription.try_recv().ok()).collect::<Vec<_>>();\n        assert!(events.iter().any(|event| matches!(\n            event,\n            GameEvent::InventoryChanged {\n                uuid: event_uuid,\n                inserted: 1,\n                item,\n            } if *event_uuid == uuid && item == "minecraft:cobblestone"\n        )));\n        assert!(events.iter().any(|event| matches!(\n            event,\n            GameEvent::InventorySlotChanged { uuid: event_uuid, .. } if *event_uuid == uuid\n        )));\n        assert!(events.iter().any(|event| matches!(\n            event,\n            GameEvent::ContainerContentChanged { uuid: event_uuid, .. } if *event_uuid == uuid\n        )));\n    }\n\n    #[test]\n    fn block_drop_enters_world_item_simulation() {'''
if old not in text or text.count(old) != 1:
    raise RuntimeError("test insertion marker missing or ambiguous")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
