use anyhow::{Context, Result};
use rom_model::{
    ClassReport, JarReport, JavaTypeReport, MemberReport, parse_field_descriptor,
    parse_method_descriptor,
};
use serde::Serialize;
use std::{
    fs::{self, File},
    io::{BufWriter, Write},
    path::Path,
};

const ACC_STATIC: u16 = 0x0008;
const ACC_INTERFACE: u16 = 0x0200;

#[derive(Debug, Clone, Serialize)]
pub struct GenerationResult {
    pub schema_version: u32,
    pub generated_files: Vec<String>,
    pub classes: Vec<GeneratedClassSummary>,
    pub warnings: Vec<GenerationWarning>,
}

#[derive(Debug, Clone, Serialize)]
pub struct GeneratedClassSummary {
    pub source_class: String,
    pub rust_symbol: String,
    pub fields: usize,
    pub methods: usize,
}

#[derive(Debug, Clone, Serialize)]
pub struct GenerationWarning {
    pub class: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub descriptor: Option<String>,
    pub code: &'static str,
    pub message: String,
}

pub fn generate_rust_skeleton(report: &JarReport, output: &Path) -> Result<GenerationResult> {
    let src_dir = output.join("src");
    fs::create_dir_all(&src_dir).with_context(|| format!("cannot create {}", src_dir.display()))?;

    let mut warnings = Vec::new();
    let mut summaries = Vec::new();
    let rust_source = render_rust_source(report, &mut warnings, &mut summaries);

    let cargo_toml = output.join("Cargo.toml");
    let lib_rs = src_dir.join("lib.rs");
    let generation_report = output.join("rom-generation-report.json");

    fs::write(&cargo_toml, render_cargo_toml())
        .with_context(|| format!("cannot write {}", cargo_toml.display()))?;
    fs::write(&lib_rs, rust_source)
        .with_context(|| format!("cannot write {}", lib_rs.display()))?;

    let result = GenerationResult {
        schema_version: 1,
        generated_files: vec![
            "Cargo.toml".to_owned(),
            "src/lib.rs".to_owned(),
            "rom-generation-report.json".to_owned(),
        ],
        classes: summaries,
        warnings,
    };

    let file = File::create(&generation_report)
        .with_context(|| format!("cannot write {}", generation_report.display()))?;
    let mut writer = BufWriter::new(file);
    serde_json::to_writer_pretty(&mut writer, &result)?;
    writer.write_all(b"\n")?;
    writer.flush()?;

    Ok(result)
}

fn render_cargo_toml() -> String {
    [
        "[package]",
        "name = \"rom-generated-skeleton\"",
        "version = \"0.1.0\"",
        "edition = \"2024\"",
        "publish = false",
        "",
        "[workspace]",
        "",
        "[lib]",
        "path = \"src/lib.rs\"",
        "",
    ]
    .join("\n")
}

fn render_rust_source(
    report: &JarReport,
    warnings: &mut Vec<GenerationWarning>,
    summaries: &mut Vec<GeneratedClassSummary>,
) -> String {
    let mut out = String::new();
    push_line(&mut out, "#![allow(dead_code)]");
    push_line(&mut out, "#![allow(unused_imports)]");
    push_line(&mut out, "#![allow(unused_variables)]");
    push_line(&mut out, "");
    push_line(
        &mut out,
        "#[doc = \"Generated by RoM. Method bodies are placeholders until bytecode lowering is implemented.\"]",
    );
    push_line(&mut out, "pub mod java_compat {");
    push_line(&mut out, "    #[derive(Debug, Clone)]");
    push_line(&mut out, "    pub struct JavaObjectRef {");
    push_line(&mut out, "        pub class_name: &'static str,");
    push_line(&mut out, "    }");
    push_line(&mut out, "");
    push_line(&mut out, "    #[derive(Debug, Clone)]");
    push_line(&mut out, "    pub struct JavaArray {");
    push_line(&mut out, "        pub component_descriptor: &'static str,");
    push_line(&mut out, "    }");
    push_line(&mut out, "");
    push_line(&mut out, "    #[derive(Debug, Clone)]");
    push_line(&mut out, "    pub struct JavaString(pub String);");
    push_line(&mut out, "");
    push_line(&mut out, "    #[derive(Debug, Clone)]");
    push_line(&mut out, "    pub enum JavaValue {");
    push_line(&mut out, "        Null,");
    push_line(&mut out, "        Object(JavaObjectRef),");
    push_line(&mut out, "        Array(JavaArray),");
    push_line(&mut out, "    }");
    push_line(&mut out, "");
    push_line(&mut out, "    #[derive(Debug, Clone)]");
    push_line(&mut out, "    pub struct JavaThrowable {");
    push_line(&mut out, "        pub class_name: &'static str,");
    push_line(&mut out, "    }");
    push_line(&mut out, "");
    push_line(
        &mut out,
        "    pub type JavaResult<T> = Result<T, JavaThrowable>;",
    );
    push_line(&mut out, "}");
    push_line(&mut out, "");
    push_line(
        &mut out,
        "use self::java_compat::{JavaArray, JavaObjectRef, JavaResult, JavaString, JavaValue};",
    );
    push_line(&mut out, "");

    for class in &report.classes {
        render_class(class, warnings, summaries, &mut out);
    }

    out
}

fn render_class(
    class: &ClassReport,
    warnings: &mut Vec<GenerationWarning>,
    summaries: &mut Vec<GeneratedClassSummary>,
    out: &mut String,
) {
    let rust_symbol = rust_type_name(&class.internal_name);
    summaries.push(GeneratedClassSummary {
        source_class: class.internal_name.clone(),
        rust_symbol: rust_symbol.clone(),
        fields: class.fields.len(),
        methods: class.methods.len(),
    });

    if class.access.bits & ACC_INTERFACE != 0 {
        render_interface(class, warnings, out, &rust_symbol);
        return;
    }

    push_doc(
        out,
        &format!("rom_source_class = {:?}", class.internal_name),
    );
    push_line(out, "#[derive(Debug, Clone)]");
    push_line(out, &format!("pub struct {rust_symbol} {{"));
    let mut instance_fields = 0usize;
    for field in &class.fields {
        if is_static(field) {
            warnings.push(GenerationWarning {
                class: class.internal_name.clone(),
                member: Some(field.name.clone()),
                descriptor: Some(field.descriptor.clone()),
                code: "static_field_not_materialized",
                message: "static Java fields require initialization policy and are reported as metadata only".to_owned(),
            });
            continue;
        }
        instance_fields += 1;
        push_doc(out, &format!("rom_source_field = {:?}", field.name));
        push_doc(
            out,
            &format!("rom_source_descriptor = {:?}", field.descriptor),
        );
        let field_name = rust_field_name(&field.name);
        let field_type = rust_type_from_descriptor(&class.internal_name, field, warnings);
        push_line(out, &format!("    pub {field_name}: {field_type},"));
    }
    if instance_fields == 0 {
        push_line(out, "    pub java_identity: JavaObjectRef,");
    }
    push_line(out, "}");
    push_line(out, "");
    push_line(out, &format!("impl {rust_symbol} {{"));
    for method in &class.methods {
        render_method(class, method, warnings, out, false);
    }
    push_line(out, "}");
    push_line(out, "");
}

fn render_interface(
    class: &ClassReport,
    warnings: &mut Vec<GenerationWarning>,
    out: &mut String,
    rust_symbol: &str,
) {
    push_doc(
        out,
        &format!("rom_source_class = {:?}", class.internal_name),
    );
    push_line(out, &format!("pub trait {rust_symbol} {{"));
    for method in &class.methods {
        render_method(class, method, warnings, out, true);
    }
    push_line(out, "}");
    push_line(out, "");
}

fn render_method(
    class: &ClassReport,
    method: &MemberReport,
    warnings: &mut Vec<GenerationWarning>,
    out: &mut String,
    in_trait: bool,
) {
    if method.name == "<clinit>" {
        warnings.push(GenerationWarning {
            class: class.internal_name.clone(),
            member: Some(method.name.clone()),
            descriptor: Some(method.descriptor.clone()),
            code: "class_initializer_placeholder",
            message: "Java class initializer needs explicit initialization policy".to_owned(),
        });
    }

    let descriptor = match parse_method_descriptor(&method.descriptor) {
        Ok(descriptor) => descriptor,
        Err(error) => {
            warnings.push(GenerationWarning {
                class: class.internal_name.clone(),
                member: Some(method.name.clone()),
                descriptor: Some(method.descriptor.clone()),
                code: "descriptor_parse_failed",
                message: error,
            });
            return;
        }
    };

    warnings.push(GenerationWarning {
        class: class.internal_name.clone(),
        member: Some(method.name.clone()),
        descriptor: Some(method.descriptor.clone()),
        code: "unsupported_method_body",
        message: "method body has not yet been lowered to Rust".to_owned(),
    });

    push_doc(
        out,
        &format!("rom_source_class = {:?}", class.internal_name),
    );
    push_doc(out, &format!("rom_source_method = {:?}", method.name));
    push_doc(
        out,
        &format!("rom_source_descriptor = {:?}", method.descriptor),
    );

    let method_name = rust_method_name(&method.name, &method.descriptor);
    let mut parameters = Vec::new();
    if !is_static(method) && method.name != "<init>" {
        parameters.push("&mut self".to_owned());
    }
    for (index, parameter) in descriptor.parameters.iter().enumerate() {
        parameters.push(format!("arg{index}: {}", rust_type(parameter)));
    }
    let return_type = if method.name == "<init>" {
        "Self".to_owned()
    } else {
        rust_type(&descriptor.return_type)
    };
    let sized_bound = if in_trait && is_static(method) {
        " where Self: Sized"
    } else {
        ""
    };
    push_line(
        out,
        &format!(
            "    pub fn {method_name}({}) -> JavaResult<{return_type}>{sized_bound} {{",
            parameters.join(", ")
        )
        .replace("pub fn", if in_trait { "fn" } else { "pub fn" }),
    );
    push_line(
        out,
        "        todo!(\"method body has not yet been lowered\")",
    );
    push_line(out, "    }");
}

fn rust_type_from_descriptor(
    class: &str,
    field: &MemberReport,
    warnings: &mut Vec<GenerationWarning>,
) -> String {
    match parse_field_descriptor(&field.descriptor) {
        Ok(ty) => rust_type(&ty),
        Err(error) => {
            warnings.push(GenerationWarning {
                class: class.to_owned(),
                member: Some(field.name.clone()),
                descriptor: Some(field.descriptor.clone()),
                code: "descriptor_parse_failed",
                message: error,
            });
            "JavaValue".to_owned()
        }
    }
}

fn rust_type(ty: &JavaTypeReport) -> String {
    match ty {
        JavaTypeReport::Byte => "i8".to_owned(),
        JavaTypeReport::Char => "char".to_owned(),
        JavaTypeReport::Double => "f64".to_owned(),
        JavaTypeReport::Float => "f32".to_owned(),
        JavaTypeReport::Int => "i32".to_owned(),
        JavaTypeReport::Long => "i64".to_owned(),
        JavaTypeReport::Short => "i16".to_owned(),
        JavaTypeReport::Boolean => "bool".to_owned(),
        JavaTypeReport::Void => "()".to_owned(),
        JavaTypeReport::Null | JavaTypeReport::Unknown { reason: _ } => "JavaValue".to_owned(),
        JavaTypeReport::Object { internal_name } if internal_name == "java/lang/String" => {
            "Option<JavaString>".to_owned()
        }
        JavaTypeReport::Object { internal_name: _ } => "Option<JavaObjectRef>".to_owned(),
        JavaTypeReport::Array {
            dimensions: _,
            component: _,
        } => "Option<JavaArray>".to_owned(),
    }
}

fn rust_type_name(internal_name: &str) -> String {
    let simple = internal_name
        .rsplit('/')
        .next()
        .filter(|value| !value.is_empty())
        .unwrap_or("GeneratedClass");
    let mut output = String::new();
    let mut capitalize = true;
    for ch in simple.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize {
                output.push(ch.to_ascii_uppercase());
                capitalize = false;
            } else {
                output.push(ch);
            }
        } else {
            capitalize = true;
        }
    }
    if output.is_empty() {
        output.push_str("GeneratedClass");
    }
    if output
        .as_bytes()
        .first()
        .is_some_and(|value| value.is_ascii_digit())
    {
        output.insert_str(0, "Class");
    }
    output
}

fn rust_field_name(java_name: &str) -> String {
    rust_identifier(java_name, "field")
}

fn rust_method_name(java_name: &str, descriptor: &str) -> String {
    let base = match java_name {
        "<init>" => "new".to_owned(),
        "<clinit>" => "class_init".to_owned(),
        value => rust_identifier(value, "method"),
    };
    format!(
        "{base}_{}",
        stable_hash(&format!("{java_name}{descriptor}"))
    )
}

fn rust_identifier(value: &str, fallback: &str) -> String {
    let mut output = String::new();
    let mut previous_underscore = false;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            output.push(ch.to_ascii_lowercase());
            previous_underscore = false;
        } else if !previous_underscore {
            output.push('_');
            previous_underscore = true;
        }
    }
    let output = output.trim_matches('_').to_owned();
    let mut output = if output.is_empty() {
        fallback.to_owned()
    } else {
        output
    };
    if output
        .as_bytes()
        .first()
        .is_some_and(|value| value.is_ascii_digit())
    {
        output.insert(0, '_');
    }
    if is_rust_keyword(&output) {
        format!("r#{output}")
    } else {
        output
    }
}

fn stable_hash(value: &str) -> String {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in value.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{:08x}", hash as u32)
}

fn is_rust_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

fn is_static(member: &MemberReport) -> bool {
    member.access.bits & ACC_STATIC != 0
}

fn push_doc(out: &mut String, value: &str) {
    push_line(out, &format!("#[doc = {}]", rust_string(value)));
}

fn rust_string(value: &str) -> String {
    let mut output = String::with_capacity(value.len() + 2);
    output.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            value if value.is_control() => output.push_str(&format!("\\u{{{:x}}}", value as u32)),
            value => output.push(value),
        }
    }
    output.push('"');
    output
}

fn push_line(out: &mut String, line: &str) {
    out.push_str(line);
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use rom_importer::{ImportOptions, inspect_jar};
    use std::{fs, path::PathBuf, process, time::SystemTime};

    #[test]
    fn generates_deterministic_rust_skeleton_and_metadata() {
        let report = inspect_fixture();
        let first_dir = unique_output_dir("first");
        let second_dir = unique_output_dir("second");

        let first = generate_rust_skeleton(&report, &first_dir).expect("generation should work");
        let second = generate_rust_skeleton(&report, &second_dir).expect("generation should work");

        let first_rust =
            fs::read_to_string(first_dir.join("src/lib.rs")).expect("generated Rust should exist");
        let second_rust =
            fs::read_to_string(second_dir.join("src/lib.rs")).expect("generated Rust should exist");
        let first_report = fs::read_to_string(first_dir.join("rom-generation-report.json"))
            .expect("generation report should exist");
        let second_report = fs::read_to_string(second_dir.join("rom-generation-report.json"))
            .expect("generation report should exist");

        assert_eq!(first_rust, second_rust);
        assert_eq!(first_report, second_report);
        assert!(first_rust.contains("pub struct BytecodeFeatures"));
        assert!(first_rust.contains("rom_source_class = \\\"m1/BytecodeFeatures\\\""));
        assert!(first_rust.contains("rom_source_descriptor = \\\"(II)I\\\""));
        assert!(first_rust.contains("todo!(\"method body has not yet been lowered\")"));
        assert!(first.warnings.iter().any(|warning| {
            warning.code == "unsupported_method_body"
                && warning.member.as_deref() == Some("arithmetic")
        }));
        assert_eq!(first.generated_files, second.generated_files);
    }

    fn inspect_fixture() -> JarReport {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/m1-bytecode/out/m1-bytecode.jar");
        let mut report = inspect_jar(
            path,
            &ImportOptions {
                class_prefix: Some("m1.BytecodeFeatures".to_owned()),
                ..ImportOptions::default()
            },
        )
        .expect("fixture should parse");
        report
            .classes
            .retain(|class| class.internal_name == "m1/BytecodeFeatures");
        report
    }

    fn unique_output_dir(label: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .expect("system clock should be after Unix epoch")
            .as_nanos();
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(format!(
            "../../target/rom-codegen-test-{}-{label}-{nanos}",
            process::id()
        ))
    }
}
